### PR TITLE
Enhance code

### PR DESCRIPTION
**Pull request by pCyril**
This PR brings code modernization to this project code with:
- composer.json file to allow fast and simple integration in other projects
- use of composer autoload in the provided examples
- use of Phpdoc annotations to specify existing magic methods
- unify coding style (simple quotes vs double quotes, PSR compliant, ...)
- Edit example code

Hope this will help.

### CODE REVIEW

**Comment by pCyril** [comment]
@codest What do you thinks about this PR ? I close it ?

**Comment by codest** [comment]
@pCyril thanks for submitting this! it looks really promising. Please give me some time to review it and merge it.

**Comment by pCyril** [comment]
Hi :)

**Comment by timmoh** [comment]
@codest any schedule for review/merge?

**Comment by pCyril** [comment]
I think it will never merged, you can use my repository https://github.com/pCyril/ahrefs-api-php

**Comment by codest** [comment]
Sorry for the wait guys. thanks for the contribution pCyril 💯

**Pull request merged**
